name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]  # Instead of ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true  # This loads the image into the local Docker daemon
        tags: scrapy-vdab-prod:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Test Docker image
      run: |
        # Run a basic test to ensure the image was built successfully
        docker run --rm scrapy-vdab-prod:latest python --version
        
    - name: Show Docker images
      run: docker images | grep scrapy-vdab-prod
